import type { Metadata } from "next";
import "../globals.css";
import Navbar from "@/components/navbarSection/Navbar";
import Footer from "@/components/footer/Footer";
import { Montserrat } from "next/font/google";
import BottomStickyContact from "@/components/common/bottomStickyContact/BottomStickyContact";

const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased`}>
        <Navbar />
        <main>{children}</main>
        <Footer />
        <div id="modal-root">
          <BottomStickyContact />
        </div>
      </body>
    </html>
  );
}
